### ISSUE TITLE
Calendar for our events

### ISSUE THREAD

**Issue by z0d14c** [uxutdallas/website#1]
Right now the calendar in the "Events" tab on the website appears to be a meetup-calendar plugin that is hooked to the UXPA's meetup calendar. That's nice but we probably want our events to be displayed instead of (or in addition to) this calendar. This issue is to track progress on that.

**Comment by z0d14c** [comment]
it looks like the whole events page is a wp-meetup plugin

**Comment by z0d14c** [comment]
I've installed a new Calendar plugin called Simple Calendar that hooks up to any public Google calendar. Right now our calendar isn't public; before making it public, I'm waiting on the OK from @linamoon . If that calendar needs to remain private, we can make a new one for only-public events. Although it would be easier to maintain just one.

**Comment by linamoon** [comment]
@z0d14c any updates on this? would like to get this up by this week at the latest - have sent you OK on slack.

**Comment by z0d14c** [comment]
done
